Http.response create binary
utily/cloudly-http pull request #43
Opened 2022-09-29 09:29 UTC by EliasEriksson

2022-09-30 17:00 UTC, simonmika requested changes

2022-10-03 06:49 UTC, EliasEriksson commented on Response/index.ts
> +						result.header.contentType = "application/json; charset=utf-8"
Broke it out but should it be placed in some other file?

2022-10-04 07:28 UTC, EliasEriksson commented on Response/index.ts
> +			result = "application/json; charset=utf-8"
Broke out the function `isPdf` and placed all the content type assignments back into the switch. Should i move the function or should it be housed exporter in the `Response` interface?

2022-10-05 07:30 UTC, simonmika approved these changes

2022-10-05 07:30 UTC, merged